openapi: 3.0.3
info:
  title: Rider Coupon API
  version: 1.0.0
  description: API for managing rider coupons (mocked using Prism)

servers:
  - url: http://localhost:4010

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation

paths:
  /intercity/v1/pickup:
    get:
      summary: Get list of pickups configured
      parameters:
        - in: header
          name: yassir-app-language
          required: false
          schema:
            type: string
          description: Preferred language for the response (e.g. en, fr, ar)
        - in: query
          name: serviceFamilyId
          required: true
          schema:
            type: string

      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response with pickup list
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  data:
                    type: array
                    nullable: true
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Object Id
                        code:
                          type: string
                          description: Optional string
                        name:
                          type: string
                          description: App language based
                        path:
                          type: string
                          description: Path string
              examples:
                with-data:
                  summary: Example with some data
                  value:
                    status: true
                    data:
                      - id: "123456788"
                        code: "11"
                        name: "Blida"
                        path: "0,192756,1258647"
                      - id: "123456788"
                        code: "12"
                        name: "Oran"
                        path: "0,192756,1258647"
                empty:
                  summary: Example with empty data
                  value:
                    status: true
                    data: []
                arabic:
                  summary: Example with arabic data
                  value:
                    status: true
                    data:
                      - id: "123456788"
                        code: "11"
                        name: "البليدة"
                        path: "0,192756,1258647"
                      - id: "123456788"
                        code: "12"
                        name: "وهران"
                        path: "0,192756,1258647"
        '400':
          description: Bad Request
          content:
            application/json:
              examples:
                pickup_error:
                  summary: Without Service Family Id
                  value:
                    status: false
                    data: null
                    errorMessageKey: "FAMILYID_REQUIRED"
                    errorMessage: "Service Family Id required"
        '500':
          description: Server error
          content:
            application/json:
              examples:
                pickup_error:
                  summary: Example error response
                  value:
                    status: false
                    data: null
                    errorMessageKey: "ERROR_PICKUP_LIST"
                    errorMessage: "Error in getting the list of pickups"   
  /intercity/v1/destination/{pickup}:
    get:
      summary: Get list of destinations for a pickup path configured
      parameters:
        - name: pickup
          in: path
          required: true
          schema:
            type: string
          description: The pickup path string
        - name: serviceFamilyId
          in: query
          required: true
          schema:
            type: string

        - in: header
          name: yassir-app-language
          required: false
          schema:
            type: string
          description: Preferred language for the response (e.g. en, fr, ar)
      responses:
        '200':
          description: Successful response with destination list
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  data:
                    type: array
                    nullable: true
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Object Id
                        code:
                          type: string
                          description: Optional string
                        name:
                          type: string
                          description: App language based
                        path:
                          type: string
                          description: Path string
              examples:
                with-data:
                  summary: Example with data
                  value:
                    status: true
                    data:
                      - id: "123456788"
                        code: "11"
                        name: "Blida"
                        path: "0,192756,1258647"
                      - id: "123456788"
                        code: "11"
                        name: "Oran"
                        path: "0,192756,1258647"
                empty:
                  summary: Example with empty data
                  value:
                    status: true
                    data: []
                arabic:
                  summary: Example with arabic data
                  value:
                    status: true
                    data:
                      - id: "123456788"
                        code: "11"
                        name: "البليدة"
                        path: "0,192756,1258647"
                      - id: "123456788"
                        code: "12"
                        name: "وهران"
                        path: "0,192756,1258647"
        '400':
          description: Bad request
          content:
            application/json:
              examples:
                destination_error_400:
                  summary: Example 400 error response
                  value:
                    status: false
                    data: null
                    errorMessageKey: "REQUIRED_FIELD_ERROR"
                    errorMessage: "Error in getting the list of destinations"
        '500':
            description: Server error
            content:
              application/json:
                examples:
                  destination_error:
                    summary: Example 500 error response
                    value:
                      status: false
                      data: null
                      errorMessageKey: "ERROR_DESTINATION_LIST"
                      errorMessage: "Error in getting the list of destinations"
  /intercity/v1/config:
    get:
      summary: Get config of a service
      parameters:
        - in: query
          name: serviceFamilyId
          required: true
          schema:
            type: string

      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response with config keys
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookingMinTime:
                    type: number
                    description: Minimum time for future booking
                  bookingMaxTime:
                    type: number
                    description: Maximum time for future booking
                  maxSeats:
                    type: number
                    description: Number of seats in car
                  path:
                    type: string
                    description: Path string
              examples:
                with-data:
                  summary: Example with some data
                  value:
                    maxSeats: 4
                    bookingMinTime: 1762142400000
                    bookingMaxTime: 1763236800000

        '500':
          description: Server error
          content:
            application/json:
              examples:
                pickup_error:
                  summary: Example error response
                  value:
                    status: false
                    data: null
                    errorMessageKey: "ERROR_INTERCITY_CONFIG"
                    errorMessage: "Error in getting the config for the service"
  /intercity/v1/search-trips:
    post:
      summary: Search available intercity trips
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                datetime:
                  type: string
                  format: date-time
                  description: Date and time for the trip (ISO 8601 format)
                pickup:
                  type: string
                  description: Pickup location identifier
                destination:
                  type: string
                  description: Destination location identifier
                seats:
                  type: number
                  description: Number of seats required
                location:
                  type: object
                  description: Location of user
                  properties:
                    lat:
                      type: string
                    lng:
                      type: string
                      
            
            examples:
              search-request:
                summary: Example search request
                value:
                  datetime: "2024-06-10T09:00:00Z"
                  pickup: "123456788"
                  destination: "123456789"
                  seats: 2
                  location:
                    lat: 3.123
                    lng: 2.123
      responses:
        200:
          description: Successful response with available trips
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  trips:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                    
                        pickup:
                          type: object
                          properties:
                            address:
                              type: string
                            city:
                              type: string
                            distance:
                              type: number
                            departureTime:
                              type: string
                              format: date-time
                            arrivalTime:
                              type: string
                              format: date-time
                        destination:
                          type: object
                          properties:
                            address:
                              type: string
                            city:
                              type: string
                        paymentMethod:
                          type: string
                  requests:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        time:
                          type: string
                          format: date-time
                        pickup:
                          type: object
                          properties:
                            city:
                              type: string
                        destination:
                          type: object
                          properties:
                            city:
                              type: string
                        

              examples:
                with-trips:
                  summary: Example with trips
                  value:
                    status: true
                    trips:
                      - id: "trip001"
                        
                        pickup:
                          address: "123 Main St"
                          city: "Blida"
                          distance: 1200
                          departureTime: "2024-06-10T09:30:00Z"
                        destination:
                          address: "456 Elm St"
                          city: "Oran"
                          arrivalTime: "2024-06-10T09:30:00Z"

                        paymentMethod: "CASH"
                        price: 2500
                        currency: DZD
                        remainingSeats: 2
                        driverProfile: 
                          id: "driver001"
                          phone: "+213600000000"
                          picture: "https://example.com/driver001.jpg"
                          name: "John Doe"
                          rating: 4.8
                          car:    
                            make: "Toyota"
                            model: "Corolla"
                            color: "Blue"
                            immat: "123-XYZ"
                      - id: "trip002"
                        pickup:
                          address: "123 Main St"
                          city: "Blida"
                          distance: 1200
                          departureTime: "2024-06-10T09:30:00Z"

                        destination:
                          address: "456 Elm St"
                          city: "Oran"
                          arrivalTime: "2024-06-10T09:30:00Z"

                        paymentMethod: "CASH"
                    requests: []
                with-requests:
                  summary: Example with requests
                  value:
                    status: true
                    requests:
                      - id: "trip001"
                        time: "2024-06-10T09:30:00Z"
                        pickup:
                          city: "Blida"
                          departureTime: "2024-06-10T09:30:00Z"

                        destination:
                          city: "Oran"
                          arrivalTime: "2024-06-10T09:30:00Z"

                        remainingSeats: 2
                     
                    trips: []
                with-requests-and-trips:
                  summary: Example with requests and trips
                  value:
                    status: true
                    requests:
                      - id: "trip001"
                        time: "2024-06-10T09:30:00Z"
                        pickup:
                          city: "Blida"
                        destination:
                          city: "Oran"
                        remainingSeats: 2
                     
                    trips:
                      - id: "trip001"
                        time: "2024-06-10T09:30:00Z"
                        pickup:
                          address: "123 Main St"
                          city: "Blida"
                        destination:
                          address: "456 Elm St"
                          city: "Oran"
                        paymentMethod: "CARD"
                        price: 2500
                        currency: DZD
                        remainingSeats: 2
                        driverProfile: 
                          id: "driver001"
                          phone: "+213600000000"
                          picture: "https://example.com/driver001.jpg"
                          name: "John Doe"
                          rating: 4.8
                          car:    
                            make: "Toyota"
                            model: "Corolla"
                            color: "Blue"
                            immat: "123-XYZ"
                      - id: "trip002"
                        time: "2024-06-10T10:00:00Z"
                        pickup:
                          address: "123 Main St"
                          city: "Blida"
                        destination:
                          address: "456 Elm St"
                          city: "Oran"
                        paymentMethod: "CASH"
                no-data:
                  summary: Example with no trips and requests
                  value:
                    status: true
                    trips: []
                    requests: []
        400:
          description: Bad request, invalid or missing parameters
          content:
            application/json:
              examples:
                bad_request:
                  summary: Example bad request response
                  value:
                    status: false
                    trips: null
                    errorMessageKey: "REQUIRED_FIELD_ERROR"
                    errorMessage: "Invalid or missing parameters"
        500:
          description: Server error
          content:
            application/json:
              examples:
                search_error:
                  summary: Example error response
                  value:
                    status: false
                    trips: null
                    errorMessageKey: "ERROR_SEARCH_TRIPS"
                    errorMessage: "Error searching for trips"
